apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: claims-api-hpa 
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: claims-api-deploy-blue
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
