{{- if .Values.ingress.enabled -}}
{{- $fullName := include "claims-api.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress-prod
  labels:
    app: {{ .Values.app.name }}
    chart: {{ template "claims-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host.epProd }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ .Values.app.name }}-svc
              servicePort: http
{{- end }}
