{{- if .Values.asesecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.asesecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
