apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  labels:
    app: {{ .Values.app.name }}
    chart: {{ template "claims-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.name }}
    slot: {{ .Values.productionSlot }}
    release: {{ .Release.Name }}
