{{ if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deploy-blue
  labels:
    app: {{ .Values.app.name }}
    chart: {{ template "claims-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      slot: blue
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        slot: blue
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ConnectionStrings__SqlServerDb
          value: "{{ .Values.sqldb.connectionString }}"
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v1/claims/healthz
            port: http
          initialDelaySeconds: {{ .Values.checks.initialDelay }}
          periodSeconds: {{ .Values.checks.periodSeconds }}
        livenessProbe:
          httpGet:
            path: /api/v1/claims/healthz
            port: http
          initialDelaySeconds: {{ .Values.checks.initialDelay }}
          periodSeconds: {{ .Values.checks.periodSeconds }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
